public class schoolss {
    public string ad;
    public string adres;
    public integer yil;

    public void ogretmen(string adiSoyadi, string brans, integer deneyim){
      system.debug(adiSoyadi+' isimli ogretmen '+ brans+' bransinda ve '+deneyim+' yil deneyimlidir.');  
    }
public void ogrenci(string isimSoyisim, integer no, integer sinif){
      system.debug(isimSoyisim+no+' numarali ogrencidir '+sinif+' nolu sinifta okuyor.');  
    }


    

}